### ISSUE TITLE
Connection leak

### ISSUE THREAD

**Issue by fabiorigo** [nuxeo/nuxeo-java-client#63]
Hello! 

We have been relying on NuxeoClient to access a Nuxeo server instance, and noticed a warning is being continuously logged in our files. 

`
2018-08-22 06:01:10,013 WARNING [] [] [okhttp3.OkHttpClient] [OkHttp ConnectionPool] A connection to http://nuxeoserver:9030/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
`

While investigating the leak, we noticed that in https://github.com/nuxeo/nuxeo-java-client/blob/master/nuxeo-java-client/src/main/java/org/nuxeo/client/marshaller/NuxeoResponseConverter.java, not always the OkHttp response body is closed. In particular, in the Jackson delegation there is no finally clause for that purpose. 

I would like to suggest that the whole `convert` method is surrounded by a `try-finally` clause that do the job. This would also mean removing the explicit calls to `body.close()` that exist in some cases.

**Comment by LSDancer** [comment]
same problem...  connections stay alive in some cases

**Comment by kevinleturc** [comment]
Hello, thanks for reporting issue. Which java client version do you use ? The on-going 3.2.0 doesn't seem to be affected by this problem, for instance there's no `body.close()` and connection is closed by try-with-resources present here: 
https://github.com/nuxeo/nuxeo-java-client/blob/master/nuxeo-java-client/src/main/java/org/nuxeo/client/marshaller/NuxeoResponseConverter.java#L111

Other use case is when downloading blob, connection has to be closed by caller, closing the `InputStream` given by `StreamBlob` does close the http connection.

**Comment by fabiorigo** [comment]
Hello @kevinleturc, we use the latest release version (3.1.0), as we cannot use unstable versions of third-party artifacts. In fact, comparing the two versions, the current one already does not have any call to `body.close()` anymore. 

Actually, my use case is when uploading a blob. I use the automation endpoint in this way: 
`
public void attachFile(String documentPath, InputStream documentStream, String fileName) {
        StreamBlob blob = new StreamBlob(documentStream, fileName);

        nuxeoClient.operation(Operations.BLOB_ATTACH_ON_DOCUMENT)
                .param("document", documentPath)
                .input(blob)
                .execute();
    }
`
In this case, do I also need to close the stream? I must point out that this stream is a file stream, not a network one.

**Comment by kevinleturc** [comment]
Hi,
There was a change in 3.1 around blob and operation. Previously the blob returned by operation was saved on the disk a temporary folder. This wasn't efficient and could cause problem on host. This was replaced by a `StreamBlob` with [JAVACLIENT-156](https://jira.nuxeo.com/browse/JAVACLIENT-156) and so you now need to close it in order to close the HTTP response.
But the correct solution if you don't want to get back the blob is to use `Operation.voidOperation(true)` before executing the call. This will tell Nuxeo server to not send back the blob, and so on client side response will be handled as any non blob response. The `voidOperation` method just add a special header documented [there](https://doc.nuxeo.com/nxdoc/special-http-headers/).

**Comment by fabiorigo** [comment]
Hi @kevinleturc, I have tried the solution proposed with `Operation.voidOperation(true)` and it solved my problem! Thanks for the clarification!!

**Comment by kevinleturc** [comment]
I'm closing the issue.
